[versions]
agp = "8.13.0"
activity = "1.10.1"
appcompat = "1.7.0"
compiler = "4.14.2"
constraintlayout = "2.2.1"
coreSplashscreen = "1.0.1"
espressoCore = "3.6.1"
glide = "4.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
lifecycleReactivestreams = "2.9.4"
lifecycleViewmodelKtx = "2.9.4"
lottie = "6.6.6"
material = "1.12.0"
navigationFragment = "2.9.0"
navigationUi = "2.9.0"
okhttpBom = "4.12.0"
pagingRuntime = "3.3.6"
pagingRxjava3 = "3.3.6"
retrofit = "3.0.0"
roomPaging = "2.8.3"
roomRuntime = "2.7.1"
dotsindicator = "5.1.0"
core = "1.16.0"
javaxInject = "1"
securityCrypto = "1.1.0"
swipeRefreshLayout = "1.1.0"

[libraries]
activity = { module = "androidx.activity:activity", version.ref = "activity" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { module = "junit:junit", version.ref = "junit" }
lifecycle-reactivestreams = { module = "androidx.lifecycle:lifecycle-reactivestreams", version.ref = "lifecycleReactivestreams" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { module = "com.google.android.material:material", version.ref = "material" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationUi" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingRuntime" }
paging-rxjava3 = { module = "androidx.paging:paging-rxjava3", version.ref = "pagingRxjava3" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-paging = { module = "androidx.room:room-paging", version.ref = "roomPaging" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
core = { module = "androidx.core:core", version.ref = "core" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipeRefreshLayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

