[versions]
agp = "9.0.0"
activity = "1.12.2"
appcompat = "1.7.1"
compiler = "5.0.5"
constraintlayout = "2.2.1"
coreSplashscreen = "1.2.0"
espressoCore = "3.7.0"
glide = "5.0.5"
junit = "4.13.2"
junitVersion = "1.3.0"
lifecycleViewmodelKtx = "2.10.0"
lottie = "6.7.1"
material = "1.13.0"
navigationFragment = "2.9.6"
navigationUi = "2.9.6"
roomPaging = "2.8.4"
roomRuntime = "2.8.4"
dotsindicator = "5.1.0"
core = "1.17.0"
swipeRefreshLayout = "1.2.0"

[libraries]
activity = { module = "androidx.activity:activity", version.ref = "activity" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { module = "junit:junit", version.ref = "junit" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { module = "com.google.android.material:material", version.ref = "material" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationUi" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-paging = { module = "androidx.room:room-paging", version.ref = "roomPaging" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
core = { module = "androidx.core:core", version.ref = "core" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipeRefreshLayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

